/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_camera_FaceDetection */

#ifndef _Included_com_example_camera_FaceDetection
#define _Included_com_example_camera_FaceDetection
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_camera_FaceDetection
 * Method:    detectFace
 * Signature: (Ljava/lang/String;Landroid/graphics/Bitmap;Landroid/graphics/Bitmap;)V
 */
JNIEXPORT void JNICALL Java_com_example_camera_FaceDetection_detectFace
  (JNIEnv *, jclass, jstring, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
